spring.application.name=Springboot

# Cau hinh ConectionPool
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size= 30
spring.datasource.hikari.minimum-idle= 10
spring.datasource.hikari.idle-timeout= 60000
spring.datasource.hikari.max-lifetime= 900000
spring.datasource.hikari.connection-timeout= 30000
spring.datasource.hikari.pool-name= MyHikariCP

# Cau hình Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Gioi han tong kich thuoc request
spring.servlet.multipart.max-request-size=20MB
# Gioi han kich thuoc moi file
spring.servlet.multipart.max-file-size=20MB

# Cau hinh jwt
jwt.signerKey=${JWT_SIGNER_KEY}
jwt.valid-duration=3600
jwt.refreshable-duration=36000

# Cau hinh api AI
ai.chatgpt.apiKey=${API_KEY_CHATGPT}
ai.chatgpt.apiUrl=${API_URL_CHATGPT}

ai.gemini.apiKey=${API_KEY_GEMINI}
ai.gemini.apiUrl=${API_URL_GEMINI}
