spring.application.name=Springboot

# Cau hinh ConectionPool
spring.datasource.url=jdbc:mysql://localhost:3306/nicehomelander
spring.datasource.username=root
spring.datasource.password=19681902
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# Cau hình Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Gioi han tong kich thuoc request
spring.servlet.multipart.max-request-size=20MB
# Gioi han kich thuoc moi file
spring.servlet.multipart.max-file-size=20MB

# Cau hinh jwt
jwt.signerKey=1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
jwt.valid-duration=3600
jwt.refreshable-duration=36000
